version: "3.9"
services:
  qdrant:
    image: qdrant/qdrant:v1.12.4
    ports:
      - "6333:6333"
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
    volumes:
      - ./qdrant_storage:/qdrant/storage
